# Generated by Django 6.0.7 on 2026-08-07 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentorganizationmapping',
            name='status',
            field=models.CharField(choices=[('pending_invitation', 'Pending Invitation'), ('active', 'Active'), ('inactive', 'Inactive'), ('removed', 'Removed')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='AgentInvitation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('used', 'Used'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_agent_invitations', to=settings.AUTH_USER_MODEL)),
                ('mapping', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='Organization.agentorganizationmapping')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='Organization.organization')),
            ],
            options={
                'verbose_name': 'Agent Invitation',
                'verbose_name_plural': 'Agent Invitations',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('organization', 'email'), name='unique_pending_invitation_per_org_email')],
            },
        ),
    ]
