x-function: &basics
  restart: unless-stopped
  networks:
    - hdr_network

services:
  postgres:
    <<: *basics
    image: postgres:15
    command: postgres -c 'max_connections=500'
    env_file:
      - ./docker/env/postgres/.env
    container_name: hdr-postgres
    hostname: hdr-postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    <<: *basics
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: hdr-web
    hostname: hdr-web
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    command: gunicorn HeyDayRealty.wsgi:application --workers 3 --bind 0.0.0.0:8000 --graceful-timeout 300 --timeout 300
    expose:
      - "8000"
    env_file:
      - ./docker/env/backend/.env
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    <<: *basics
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        NGINX_CONFIG: default.prod.conf.tpl
    container_name: hdr-nginx
    hostname: hdr-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web

  db-backup:
    image: postgres:15
    container_name: hdr-postgres-backup
    restart: unless-stopped
    networks:
      - hdr_network

    env_file:
      - ./docker/env/postgres/.env

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./backups/postgres:/backups

    entrypoint: /bin/sh

    command:
      - -c
      - |
        set -e

        while true; do
          echo "======================================"
          echo "Creating PostgreSQL backup..."
          echo "Database: $$POSTGRES_DB"
          echo "User: $$POSTGRES_USER"

          PGPASSWORD="$$POSTGRES_PASSWORD" pg_dump \
            -h postgres \
            -U "$$POSTGRES_USER" \
            -d "$$POSTGRES_DB" \
            -Fc \
            -f "/backups/postgres_$$(date +%Y-%m-%d_%H-%M-%S).dump"

          echo "Backup completed."

          ls -lh /backups

          find /backups -type f -name "*.dump" -mtime +7 -delete

          echo "Waiting 24 hours..."

          sleep 86400
        done

networks:
  hdr_network:
    name: hdr_default

volumes:
  postgres_data:
  static_volume:
  media_volume:
