# Generated by Django 5.2.15 on 2026-06-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0002_agentprofile_commission_rate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyInquiry',
        ),
    ]
