# Generated by Django 5.2.6 on 2026-07-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0003_delete_propertyinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='address_proof_document',
            field=models.FileField(blank=True, null=True, upload_to='agent_verification/address_proof/'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='id_proof_document',
            field=models.FileField(blank=True, null=True, upload_to='agent_verification/id_proof/'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='verification_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='verification_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_started', max_length=20),
        ),
    ]
