# Generated by Django 6.0.6 on 2026-07-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0004_agentprofile_address_proof_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Full address'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, help_text='Alternate contact number', max_length=20),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
