# Generated by Django 6.0.6 on 2026-08-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0005_agentprofile_address_agentprofile_alternate_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
