# Generated by Django 5.2.6 on 2026-08-03 09:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0005_agentprofile_address_agentprofile_alternate_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='id_proof_document',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\HeyDay\\HDR\\private_media'), upload_to='agent_verification/id_proof/'),
        ),
    ]
