# Generated by Django 5.2.16 on 2026-07-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0005_agentprofile_address_agentprofile_alternate_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='id_proof_back_document',
            field=models.FileField(blank=True, null=True, upload_to='agent_verification/id_proof_back/'),
        ),
    ]
