# Generated by Django 6.0.6 on 2026-08-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0006_agentprofile_id_proof_back_document'),
        ('Agent', '0006_alter_lead_phone'),
    ]

    operations = [
    ]
