# Generated by Django 6.0.6 on 2026-08-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0007_merge_20260801_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='id_proof_back_document',
        ),
    ]
