# Generated by Django 6.0.7 on 2026-08-12 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0008_remove_agentprofile_id_proof_back_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('voter_id', 'Voter ID'), ('driving_license', 'Driving License'), ('passport', 'Passport'), ('address_proof', 'Address Proof'), ('bank_statement', 'Bank Statement'), ('gst_certificate', 'GST Certificate'), ('other', 'Other')], max_length=30)),
                ('document_name', models.CharField(blank=True, help_text='Custom name when document type is Other', max_length=200)),
                ('front_file', models.FileField(upload_to='agent_verification/front/')),
                ('back_file', models.FileField(blank=True, null=True, upload_to='agent_verification/back/')),
                ('has_back_side', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('reupload_required', 'Re-upload Required')], default='pending_review', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True, help_text='False for historical submissions kept after re-upload')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verification_documents', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to=settings.AUTH_USER_MODEL)),
                ('replaces', models.ForeignKey(blank=True, help_text='Previous submission this re-upload replaces', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='Agent.verificationdocument')),
            ],
            options={
                'verbose_name': 'Verification Document',
                'verbose_name_plural': 'Verification Documents',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
