# Generated by Django 6.0.6 on 2026-09-01 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0010_migrate_legacy_verification_proofs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(help_text='Name of the reviewer', max_length=100)),
                ('reviewer_email', models.EmailField(blank=True, help_text='Email of the reviewer (optional)', max_length=254)),
                ('reviewer_phone', models.CharField(blank=True, help_text='Phone of the reviewer (optional)', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Star rating (1-5)')),
                ('review_text', models.TextField(help_text='Review description/thoughts')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Review moderation status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Agent.agentprofile')),
            ],
            options={
                'verbose_name': 'Agent Review',
                'verbose_name_plural': 'Agent Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
