# Generated by Django 6.0.6 on 2026-09-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0011_agentreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentreview',
            name='status',
        ),
    ]
