# Generated by Django 6.0.5 on 2026-09-17 05:22

import HeyDayRealty.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0012_remove_agentreview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='address_proof_document',
            field=models.FileField(blank=True, null=True, storage=HeyDayRealty.storage_backends.AgentMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_agent_address_proof_path),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='id_proof_document',
            field=models.FileField(blank=True, null=True, storage=HeyDayRealty.storage_backends.AgentMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_agent_id_proof_path),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=HeyDayRealty.storage_backends.AgentMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_agent_profile_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=HeyDayRealty.storage_backends.AgentMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_agent_document_path),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='back_file',
            field=models.FileField(blank=True, null=True, storage=HeyDayRealty.storage_backends.AgentMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_agent_verification_back_path),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='front_file',
            field=models.FileField(storage=HeyDayRealty.storage_backends.AgentMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_agent_verification_front_path),
        ),
    ]
