# Generated by Django 5.2.10 on 2026-01-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('Apartments', 'Apartments / Condos'), ('Villas', 'Villas / Independent Houses'), ('Commercial', 'Commercial Properties'), ('Luxury', 'Luxury Properties'), ('Plots', 'Plots / Land')], default='Apartments', max_length=20),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Interiors', 'Interiors'), ('Amenities', 'Amenities'), ('Neighborhood', 'Neighborhood / Lifestyle')], default='General', max_length=20),
        ),
    ]
