# Generated by Django 5.2.10 on 2026-03-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0002_property_category_propertyimage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='allowed_roles',
            field=models.CharField(choices=[('all', 'All Users'), ('customer', 'Customers Only'), ('investor', 'Investors Only'), ('admin', 'Admin Only')], default='all', help_text='Roles that can access this property', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='expected_roi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected ROI percentage (investors only)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='investment_opportunity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='minimum_investment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum investment amount (investors only)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='public_description',
            field=models.TextField(default=1, help_text='Brief description shown to public visitors (max 200 characters)', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='requires_authentication',
            field=models.BooleanField(default=False, help_text='Require authentication to view full details'),
        ),
        migrations.AddField(
            model_name='property',
            name='show_to_public',
            field=models.BooleanField(default=True, help_text='Show property to unauthenticated visitors'),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(help_text='Full description only visible to authenticated users'),
        ),
    ]
