# Generated by Django 6.0.6 on 2026-06-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0004_property_seller_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='farmhouse_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='google_map_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='plantation_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_sizes',
            field=models.CharField(blank=True, help_text='Example: 5000 Sq Ft - 1 Acre', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='project_size_acre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='registry_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='road_access',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='soil_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='water_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('Managed Farmland', 'Managed Farmland'), ('Agricultural Land', 'Agricultural Land'), ('Farm Plots', 'Farm Plots'), ('Weekend Farm', 'Weekend Farm'), ('Investment Farmland', 'Investment Farmland')], default='Apartments', max_length=20),
        ),
    ]
