# Generated by Django 5.2.15 on 2026-06-07 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0004_property_seller_property_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area_unit',
            field=models.CharField(blank=True, choices=[('sqft', 'Sq.ft'), ('sqyard', 'Sq.Yard'), ('acre', 'Acre'), ('bigha', 'Bigha'), ('hectare', 'Hectare')], help_text='Area Unit', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='Assigned Agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='balconies',
            field=models.PositiveIntegerField(blank=True, help_text='Number of Balconies', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bhk_configuration',
            field=models.CharField(blank=True, help_text='BHK Configuration (e.g., 2BHK, 3BHK)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='booking_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Booking Amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='boundary_wall',
            field=models.BooleanField(default=False, help_text='Boundary Wall'),
        ),
        migrations.AddField(
            model_name='property',
            name='building_approval',
            field=models.FileField(blank=True, help_text='Building Approval', null=True, upload_to='properties/documents/approval/'),
        ),
        migrations.AddField(
            model_name='property',
            name='built_up_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Built-up Area (in sq.ft)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='carpet_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Carpet Area (in sq.ft)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cctv',
            field=models.BooleanField(default=False, help_text='CCTV'),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='club_house_access',
            field=models.BooleanField(default=False, help_text='Club House Access'),
        ),
        migrations.AddField(
            model_name='property',
            name='completion_certificate',
            field=models.FileField(blank=True, help_text='Completion Certificate', null=True, upload_to='properties/documents/completion/'),
        ),
        migrations.AddField(
            model_name='property',
            name='corner_plot',
            field=models.BooleanField(default=False, help_text='Corner Plot'),
        ),
        migrations.AddField(
            model_name='property',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Created By', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(blank=True, help_text='District', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Down Payment', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='drone_video',
            field=models.FileField(blank=True, help_text='Drone Video', null=True, upload_to='properties/videos/drone/'),
        ),
        migrations.AddField(
            model_name='property',
            name='electricity_availability',
            field=models.BooleanField(default=False, help_text='Electricity Availability'),
        ),
        migrations.AddField(
            model_name='property',
            name='emi_availability',
            field=models.BooleanField(default=False, help_text='EMI Availability'),
        ),
        migrations.AddField(
            model_name='property',
            name='facing_direction',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('north_east', 'North-East'), ('north_west', 'North-West'), ('south_east', 'South-East'), ('south_west', 'South-West')], help_text='Facing Direction', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured Image', null=True, upload_to='properties/featured/'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_plan',
            field=models.ImageField(blank=True, help_text='Floor Plan Image', null=True, upload_to='properties/floorplans/'),
        ),
        migrations.AddField(
            model_name='property',
            name='front_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Front Width (in feet)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='full_address',
            field=models.TextField(blank=True, help_text='Full Address', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing_status',
            field=models.CharField(blank=True, choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-Furnished'), ('fully_furnished', 'Fully-Furnished')], help_text='Furnishing Status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='garden',
            field=models.BooleanField(default=False, help_text='Garden'),
        ),
        migrations.AddField(
            model_name='property',
            name='google_map_location',
            field=models.URLField(blank=True, help_text='Google Map Location', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='gym',
            field=models.BooleanField(default=False, help_text='Gym'),
        ),
        migrations.AddField(
            model_name='property',
            name='inquiry_count',
            field=models.PositiveIntegerField(default=0, help_text='Inquiry Count'),
        ),
        migrations.AddField(
            model_name='property',
            name='irrigation_facility',
            field=models.BooleanField(default=False, help_text='Irrigation Facility'),
        ),
        migrations.AddField(
            model_name='property',
            name='khasra_number',
            field=models.CharField(blank=True, help_text='Khasra Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='khata_number',
            field=models.CharField(blank=True, help_text='Khata Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_category',
            field=models.CharField(blank=True, choices=[('agricultural', 'Agricultural'), ('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], help_text='Land Category', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='landmark',
            field=models.CharField(blank=True, help_text='Landmark', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, help_text='Last Updated By', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='layout_plan',
            field=models.FileField(blank=True, help_text='Layout Plan', null=True, upload_to='properties/documents/layout/'),
        ),
        migrations.AddField(
            model_name='property',
            name='lead_count',
            field=models.PositiveIntegerField(default=0, help_text='Lead Count'),
        ),
        migrations.AddField(
            model_name='property',
            name='locality',
            field=models.CharField(blank=True, help_text='Locality', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='maintenance_charges',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maintenance Charges (monthly)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='modular_kitchen',
            field=models.BooleanField(default=False, help_text='Modular Kitchen'),
        ),
        migrations.AddField(
            model_name='property',
            name='mutation',
            field=models.FileField(blank=True, help_text='Mutation Document', null=True, upload_to='properties/documents/mutation/'),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_facilities',
            field=models.TextField(blank=True, help_text='Nearby Facilities and Distances', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='negotiable',
            field=models.BooleanField(default=False, help_text='Negotiable'),
        ),
        migrations.AddField(
            model_name='property',
            name='noc',
            field=models.FileField(blank=True, help_text='NOC Document', null=True, upload_to='properties/documents/noc/'),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_floors',
            field=models.PositiveIntegerField(blank=True, help_text='Number of Floors', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_availability',
            field=models.BooleanField(default=False, help_text='Parking Availability'),
        ),
        migrations.AddField(
            model_name='property',
            name='pincode',
            field=models.CharField(blank=True, help_text='Pincode', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Plot Area (in sq.ft)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Plot Depth (in feet)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_number',
            field=models.CharField(blank=True, help_text='Plot Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='possession_status',
            field=models.CharField(blank=True, choices=[('ready_to_move', 'Ready to Move'), ('under_construction', 'Under Construction'), ('new_launch', 'New Launch')], help_text='Possession Status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='power_backup',
            field=models.BooleanField(default=False, help_text='Power Backup'),
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price Per Sq.ft', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_age',
            field=models.PositiveIntegerField(blank=True, help_text='Property Age (in years)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_brochure',
            field=models.FileField(blank=True, help_text='Property Brochure PDF', null=True, upload_to='properties/documents/brochure/'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_owner',
            field=models.CharField(blank=True, help_text='Property Owner Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_video',
            field=models.FileField(blank=True, help_text='Property Video', null=True, upload_to='properties/videos/'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_views_count',
            field=models.PositiveIntegerField(default=0, help_text='Property Views Count'),
        ),
        migrations.AddField(
            model_name='property',
            name='registry_copy',
            field=models.FileField(blank=True, help_text='Registry Copy', null=True, upload_to='properties/documents/registry/'),
        ),
        migrations.AddField(
            model_name='property',
            name='registry_number',
            field=models.CharField(blank=True, help_text='Registry Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='road_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Road Width (in feet)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_deed',
            field=models.FileField(blank=True, help_text='Sale Deed', null=True, upload_to='properties/documents/sale_deed/'),
        ),
        migrations.AddField(
            model_name='property',
            name='security',
            field=models.BooleanField(default=False, help_text='Security'),
        ),
        migrations.AddField(
            model_name='property',
            name='sewer_availability',
            field=models.BooleanField(default=False, help_text='Sewer Availability'),
        ),
        migrations.AddField(
            model_name='property',
            name='smart_home_features',
            field=models.BooleanField(default=False, help_text='Smart Home Features'),
        ),
        migrations.AddField(
            model_name='property',
            name='source_tracking',
            field=models.CharField(blank=True, help_text='Source Tracking', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, help_text='State', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='store_room',
            field=models.BooleanField(default=False, help_text='Store Room'),
        ),
        migrations.AddField(
            model_name='property',
            name='swimming_pool',
            field=models.BooleanField(default=False, help_text='Swimming Pool'),
        ),
        migrations.AddField(
            model_name='property',
            name='terrace',
            field=models.BooleanField(default=False, help_text='Terrace'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Area', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='virtual_tour_360',
            field=models.URLField(blank=True, help_text='360° Virtual Tour URL', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='water_availability',
            field=models.BooleanField(default=False, help_text='Water Availability'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area_sqft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
