# Generated by Django 5.2.15 on 2026-06-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0005_property_area_unit_property_assigned_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agri_land_category',
            field=models.CharField(blank=True, choices=[('agricultural_land', 'Agricultural Land'), ('farmland', 'Farmland'), ('plantation_land', 'Plantation Land'), ('organic_farming_land', 'Organic Farming Land'), ('agro_investment_land', 'Agro Investment Land')], help_text='Agricultural Land Category', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='airport_distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Airport Distance (km)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='appreciation_potential',
            field=models.CharField(blank=True, help_text='Appreciation Potential', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='borewell_available',
            field=models.BooleanField(default=False, help_text='Borewell Available'),
        ),
        migrations.AddField(
            model_name='property',
            name='boundary_available',
            field=models.BooleanField(default=False, help_text='Boundary Available'),
        ),
        migrations.AddField(
            model_name='property',
            name='canal_water',
            field=models.BooleanField(default=False, help_text='Canal Water'),
        ),
        migrations.AddField(
            model_name='property',
            name='crop_suitability',
            field=models.CharField(blank=True, choices=[('wheat', 'Wheat'), ('rice', 'Rice'), ('sugarcane', 'Sugarcane'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('mixed_farming', 'Mixed Farming')], help_text='Crop Suitability', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='current_usage',
            field=models.CharField(blank=True, choices=[('farming', 'Farming'), ('plantation', 'Plantation'), ('dairy', 'Dairy'), ('agro_investment', 'Agro Investment'), ('vacant_land', 'Vacant Land')], help_text='Current Usage', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='farm_house_available',
            field=models.BooleanField(default=False, help_text='Farm House Available'),
        ),
        migrations.AddField(
            model_name='property',
            name='fencing_available',
            field=models.BooleanField(default=False, help_text='Fencing Available'),
        ),
        migrations.AddField(
            model_name='property',
            name='highway_distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Highway Distance (km)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='investment_type',
            field=models.CharField(blank=True, choices=[('agriculture', 'Agriculture'), ('long_term_investment', 'Long-Term Investment'), ('plantation', 'Plantation'), ('agro_business', 'Agro Business')], help_text='Investment Type', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='keywords',
            field=models.CharField(blank=True, help_text='Keywords (comma-separated)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_code',
            field=models.CharField(blank=True, help_text='Auto-generated Land Code', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_level',
            field=models.CharField(blank=True, choices=[('flat', 'Flat'), ('semi_flat', 'Semi Flat'), ('hilly', 'Hilly')], help_text='Land Level', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_shape',
            field=models.CharField(blank=True, choices=[('square', 'Square'), ('rectangle', 'Rectangle'), ('irregular', 'Irregular')], help_text='Land Shape', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('under_verification', 'Under Verification')], default='available', help_text='Land Status', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='legal_status',
            field=models.CharField(blank=True, choices=[('clear_title', 'Clear Title'), ('under_verification', 'Under Verification'), ('litigation', 'Litigation')], help_text='Legal Status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='market_distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Market Distance (km)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_village_distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nearest Village Distance (km)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_email',
            field=models.EmailField(blank=True, help_text='Owner Email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_mobile',
            field=models.CharField(blank=True, help_text='Owner Mobile', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Owner Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('joint_ownership', 'Joint Ownership'), ('company', 'Company'), ('trust', 'Trust')], help_text='Ownership Type', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_acre',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price Per Acre', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_highlights',
            field=models.TextField(blank=True, help_text='Property Highlights', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='railway_station_distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Railway Station Distance (km)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rainwater_harvesting',
            field=models.BooleanField(default=False, help_text='Rainwater Harvesting'),
        ),
        migrations.AddField(
            model_name='property',
            name='revenue_village',
            field=models.CharField(blank=True, help_text='Revenue Village', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='road_connectivity',
            field=models.CharField(blank=True, help_text='Road Connectivity', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='seo_description',
            field=models.TextField(blank=True, help_text='SEO Description', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='seo_title',
            field=models.CharField(blank=True, help_text='SEO Title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('black_soil', 'Black Soil'), ('red_soil', 'Red Soil'), ('alluvial_soil', 'Alluvial Soil'), ('sandy_soil', 'Sandy Soil'), ('mixed_soil', 'Mixed Soil')], help_text='Soil Type', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='solar_facility',
            field=models.BooleanField(default=False, help_text='Solar Facility'),
        ),
        migrations.AddField(
            model_name='property',
            name='storage_facility',
            field=models.BooleanField(default=False, help_text='Storage Facility'),
        ),
        migrations.AddField(
            model_name='property',
            name='tehsil',
            field=models.CharField(blank=True, help_text='Tehsil', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_land_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Land Price', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='tube_well',
            field=models.BooleanField(default=False, help_text='Tube Well'),
        ),
        migrations.AddField(
            model_name='property',
            name='village',
            field=models.CharField(blank=True, help_text='Village', max_length=200, null=True),
        ),
    ]
