# Generated by Django 6.0.6 on 2026-06-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0005_property_farmhouse_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='project_highlights',
            field=models.TextField(blank=True, help_text='One highlight per line'),
        ),
    ]
