# Generated by Django 5.2.15 on 2026-06-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0006_property_agri_land_category_and_more'),
    ]

    operations = []
