# Generated by Django 5.2.10 on 2026-06-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0007_auto_20260614_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='project_highlights',
        ),
    ]
