# Generated by Django 5.2.6 on 2026-07-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0010_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='investment_budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
