# Generated by Django 5.2.6 on 2026-07-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0011_alter_inquiry_investment_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='enquiry_id',
            field=models.CharField(blank=True, editable=False, max_length=5, unique=True),
        ),
    ]
