# Generated by Django 5.2.6 on 2026-07-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0012_inquiry_enquiry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='source',
            field=models.CharField(default='Website Contact Form', max_length=100),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('interested', 'Interested'), ('site_visit_scheduled', 'Site Visit Scheduled'), ('converted', 'Converted'), ('closed', 'Closed'), ('spam', 'Spam')], default='pending', max_length=20),
        ),
    ]
