# Generated by Django 5.2.6 on 2026-07-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0013_inquiry_ip_address_inquiry_source_inquiry_user_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes, visible only to admin', null=True),
        ),
    ]
