# Generated by Django 5.2.6 on 2026-07-03 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0014_inquiry_admin_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('interested', 'Interested'), ('site_visit_scheduled', 'Site Visit Scheduled'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='WebsiteEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_id', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('investment_budget', models.CharField(blank=True, choices=[('under_5L', 'Under ₹5 Lakh'), ('5L_10L', '₹5 Lakh – ₹10 Lakh'), ('10L_25L', '₹10 Lakh – ₹25 Lakh'), ('25L_50L', '₹25 Lakh – ₹50 Lakh'), ('50L_1Cr', '₹50 Lakh – ₹1 Crore'), ('above_1Cr', 'Above ₹1 Crore')], max_length=50, null=True, verbose_name='Investment Budget')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('interested', 'Interested'), ('site_visit_scheduled', 'Site Visit Scheduled'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=25, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes — visible only to admin', null=True, verbose_name='Admin Notes')),
                ('source', models.CharField(default='Website Contact Form', max_length=100, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_enquiries', to=settings.AUTH_USER_MODEL, verbose_name='User Interface')),
            ],
            options={
                'verbose_name': 'Website Enquiry',
                'verbose_name_plural': 'Website Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
