# Generated by Django 6.0.6 on 2026-07-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0015_alter_inquiry_status_websiteenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('geo_name_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('timezone', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=1)),
                ('display_name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Location Data',
                'verbose_name_plural': 'Location Data',
                'ordering': ['sort_order', 'city'],
            },
        ),
    ]
