# Generated by Django 5.2.6 on 2026-07-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0015_alter_inquiry_status_websiteenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_highlights',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
