# Generated by Django 6.0.6 on 2026-07-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0016_locationdata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='locationdata',
            table='location',
        ),
    ]
