# Generated by Django 5.2.6 on 2026-07-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0016_alter_property_property_highlights'),
        ('PublicPage', '0017_alter_locationdata_table'),
    ]

    operations = [
    ]
