# Generated by Django 5.2.6 on 2026-07-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0018_merge_20260712_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_admin_list',
            field=models.BooleanField(default=False, help_text='If True, the property is for Admin only and will not show on the public web page'),
        ),
    ]
