# Generated by Django 5.2.6 on 2026-07-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0019_property_is_admin_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='enquiry_id',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed')], default='new', max_length=10),
        ),
    ]
