# Generated by Django 5.2.6 on 2026-07-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0020_contactinquiry_enquiry_id_contactinquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='enquiry_id',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
