# Generated by Django 5.2.6 on 2026-07-20 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0004_agentprofile_address_proof_document_and_more'),
        ('PublicPage', '0021_alter_contactinquiry_enquiry_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyinquiry',
            name='property',
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='agent_profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_inquiries', to='Agent.agentprofile'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='enquiry_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='related_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_inquiries_set', to='PublicPage.property'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed')], default='new', max_length=20),
        ),
    ]
