# Generated by Django 5.2.6 on 2026-07-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0022_remove_propertyinquiry_property_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyinquiry',
            old_name='agent_profile_id',
            new_name='agent_profile',
        ),
        migrations.AlterField(
            model_name='propertyinquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='propertyinquiry',
            name='enquiry_id',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
