# Generated by Django 6.0.5 on 2026-09-17 05:22

import HeyDayRealty.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicPage', '0024_propertyinquiry_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_approval',
            field=models.FileField(blank=True, help_text='Building Approval', null=True, storage=HeyDayRealty.storage_backends.PropertyMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_property_image_path),
        ),
        migrations.AlterField(
            model_name='property',
            name='completion_certificate',
            field=models.FileField(blank=True, help_text='Completion Certificate', null=True, storage=HeyDayRealty.storage_backends.PropertyMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_property_image_path),
        ),
        migrations.AlterField(
            model_name='property',
            name='drone_video',
            field=models.FileField(blank=True, help_text='Drone Video', null=True, storage=HeyDayRealty.storage_backends.PropertyMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_property_image_path),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured Image', null=True, storage=HeyDayRealty.storage_backends.PropertyMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_property_image_path),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_plan',
            field=models.ImageField(blank=True, help_text='Floor Plan Image', null=True, storage=HeyDayRealty.storage_backends.PropertyMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_property_image_path),
        ),
        migrations.AlterField(
            model_name='property',
            name='layout_plan',
            field=models.FileField(blank=True, help_text='Layout Plan', null=True, storage=HeyDayRealty.storage_backends.PropertyMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_property_image_path),
        ),
        migrations.AlterField(
            model_name='property',
            name='mutation',
            field=models.FileField(blank=True, help_text='Mutation Document', null=True, storage=HeyDayRealty.storage_backends.PropertyMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_property_image_path),
        ),
        migrations.AlterField(
            model_name='property',
            name='noc',
            field=models.FileField(blank=True, help_text='NOC Document', null=True, storage=HeyDayRealty.storage_backends.PropertyMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_property_image_path),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_brochure',
            field=models.FileField(blank=True, help_text='Property Brochure PDF', null=True, storage=HeyDayRealty.storage_backends.PropertyMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_property_image_path),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_video',
            field=models.FileField(blank=True, help_text='Property Video', null=True, storage=HeyDayRealty.storage_backends.PropertyMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_property_image_path),
        ),
        migrations.AlterField(
            model_name='property',
            name='registry_copy',
            field=models.FileField(blank=True, help_text='Registry Copy', null=True, storage=HeyDayRealty.storage_backends.PropertyMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_property_image_path),
        ),
        migrations.AlterField(
            model_name='property',
            name='sale_deed',
            field=models.FileField(blank=True, help_text='Sale Deed', null=True, storage=HeyDayRealty.storage_backends.PropertyMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_property_image_path),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(storage=HeyDayRealty.storage_backends.PropertyMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_property_image_path),
        ),
    ]
