# Generated by Django 5.2.6 on 2026-07-15 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planfeature',
            options={'ordering': ['plan', 'display_order'], 'verbose_name': 'Plan Feature', 'verbose_name_plural': 'Plan Features'},
        ),
        migrations.AlterModelOptions(
            name='planpricing',
            options={'ordering': ['plan', 'billing_cycle'], 'verbose_name': 'Plan Pricing', 'verbose_name_plural': 'Plan Pricing'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AlterUniqueTogether(
            name='planfeature',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique Slug e.g. seed (auto-generated if left blank)', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='display_order',
            field=models.PositiveIntegerField(default=1, help_text='Ordering of feature row'),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='feature_name',
            field=models.CharField(help_text='Feature Name e.g. Active Listings', max_length=150),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='feature_value',
            field=models.CharField(blank=True, help_text='Displayed Value e.g. 50 / Unlimited / Yes', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Show tick or cross'),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='plan',
            field=models.ForeignKey(help_text='Plan', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='Subscriptions.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='planpricing',
            name='billing_cycle',
            field=models.CharField(choices=[('1M', 'Monthly (1 Month)'), ('3M', 'Quarterly (3 Months)'), ('6M', 'Half Yearly (6 Months)'), ('12M', 'Yearly (12 Months)')], help_text='1M/3M/6M/12M', max_length=3),
        ),
        migrations.AlterField(
            model_name='planpricing',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default Billing cycle to pre-select'),
        ),
        migrations.AlterField(
            model_name='planpricing',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Old Price (for showing strike-through discount)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='planpricing',
            name='plan',
            field=models.ForeignKey(help_text='Related Plan', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='Subscriptions.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='planpricing',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling Price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='planpricing',
            name='save_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='Discount %', null=True),
        ),
        migrations.AlterField(
            model_name='planpricing',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Badge e.g. Most Popular', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='button_text',
            field=models.CharField(default='Choose Plan', help_text='Button Text e.g. Choose Plan', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='button_url',
            field=models.CharField(blank=True, help_text='Button Link e.g. /checkout', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='display_order',
            field=models.PositiveIntegerField(default=1, help_text='Ordering on the pricing page'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Status'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(help_text='Plan Name e.g. Seed', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='short_description',
            field=models.CharField(blank=True, help_text='Subtitle e.g. Forever Free', max_length=255, null=True),
        ),
    ]
