# Generated by Django 5.2.15 on 2026-07-18 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0002_alter_planfeature_options_alter_planpricing_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='badge_image',
            field=models.ImageField(blank=True, help_text='Plan Logo/Badge (e.g. Seed/Harvest icon)', null=True, upload_to='plan_badges/'),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, help_text='Start Date')),
                ('end_date', models.DateTimeField(blank=True, help_text='Expiry Date', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', help_text='Subscription Status', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe ID', max_length=150, null=True)),
                ('auto_renew', models.BooleanField(default=True, help_text='Auto Renew')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(help_text='Purchased Plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='Subscriptions.subscriptionplan')),
                ('pricing', models.ForeignKey(blank=True, help_text='Billing Cycle Chosen (optional for free plans)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subscriptions.planpricing')),
                ('user', models.OneToOneField(help_text='Subscriber', on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
            },
        ),
    ]
