# Generated by Django 5.2.15 on 2026-07-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0003_subscriptionplan_badge_image_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='property_limit',
            field=models.PositiveIntegerField(default=10, help_text='Max properties an agent can list on this plan'),
        ),
    ]
