# Generated by Django 5.2.15 on 2026-07-21 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0005_paymenttransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit (Money In)'), ('DEBIT', 'Debit (Money Out)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount involved', max_digits=10)),
                ('balance_after_transaction', models.DecimalField(decimal_places=2, help_text='Running balance of the user after this entry', max_digits=12)),
                ('description', models.CharField(help_text='e.g. Subscription Purchase - Harvest Plan', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='Subscriptions.paymenttransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
