# Generated by Django 5.2.6 on 2026-07-30 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0006_ledgerentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='planfeature',
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Feature Name (e.g. Active Listings)', max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan Feature',
                'verbose_name_plural': 'Plan Features',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_value', models.CharField(blank=True, help_text='Example: 50, Unlimited, Yes', max_length=100, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Show tick or cross')),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='Subscriptions.planfeature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='Subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription Plan Feature',
                'verbose_name_plural': 'Subscription Plan Features',
                'ordering': ['plan', 'display_order'],
                'unique_together': {('plan', 'feature')},
            },
        ),
    ]
