# Generated by Django 5.2.15 on 2026-08-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0007_alter_planfeature_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planpricing',
            name='stripe_price_id',
        ),
        migrations.AddField(
            model_name='planpricing',
            name='cashfree_plan_id',
            field=models.CharField(blank=True, help_text='Cashfree Subscriptions Plan ID (e.g. HARVEST_1M)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='property_limit',
            field=models.PositiveIntegerField(default=10, help_text='Max properties an agent can list on this plan. Use 0 for unlimited.'),
        ),
    ]
