# Generated by Django 5.2.15 on 2026-06-09 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0001_initial'),
        ('PublicPage', '0005_property_area_unit_property_assigned_agent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmitted', 'Resubmitted')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (required if rejected)', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes during review', null=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmissions', to='Administration.propertyreview')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='PublicPage.property')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Review',
                'verbose_name_plural': 'Property Reviews',
                'ordering': ['-reviewed_at'],
                'indexes': [models.Index(fields=['property', '-reviewed_at'], name='Administrat_propert_d969a1_idx'), models.Index(fields=['status', '-reviewed_at'], name='Administrat_status_4b1f0e_idx'), models.Index(fields=['reviewed_by', '-reviewed_at'], name='Administrat_reviewe_c0dab7_idx')],
            },
        ),
    ]
