# Generated by Django 6.0.7 on 2026-07-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0003_adminprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('preferred_contact_method', models.CharField(max_length=100)),
                ('property_type', models.CharField(blank=True, max_length=100)),
                ('preferred_location', models.CharField(blank=True, max_length=255)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('area_size', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'website_inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
