# Generated by Django 6.0.6 on 2026-08-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_customerprofile_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyViewing',
        ),
    ]
