# Generated by Django 6.0.5 on 2026-09-17 05:22

import HeyDayRealty.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_delete_propertyviewing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=HeyDayRealty.storage_backends.CustomerMediaStorage(), upload_to=HeyDayRealty.storage_backends.get_customer_profile_path),
        ),
    ]
