# Generated by Django 5.2.15 on 2026-06-16 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0001_initial'),
        ('PublicPage', '0007_auto_20260614_1357'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current value of investment', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='exit_date',
            field=models.DateTimeField(blank=True, help_text='Date when investment was exited', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='exit_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Value at exit', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='last_valuation_date',
            field=models.DateTimeField(blank=True, help_text='Date of last valuation update', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Profit or loss amount', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='profit_loss_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Profit/loss percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='bank_account_type',
            field=models.CharField(blank=True, choices=[('savings', 'Savings'), ('current', 'Current')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='kyc_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc_documents/'),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='pan_number',
            field=models.CharField(blank=True, help_text='Permanent Account Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax identification number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='tax_residency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='InvestmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('portfolio', 'Portfolio Report'), ('investment', 'Investment Report'), ('roi', 'ROI Report'), ('tax', 'Tax Report'), ('annual', 'Annual Report')], max_length=20)),
                ('report_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], default='pdf', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='investment_reports/')),
                ('data_snapshot', models.JSONField(blank=True, help_text='Snapshot of data at report generation time', null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('appreciation_alert', 'Property Appreciation Alert'), ('investment_update', 'Investment Update'), ('document_update', 'Document Update'), ('new_opportunity', 'New Investment Opportunity'), ('admin_message', 'Admin Message'), ('request_approved', 'Investment Request Approved'), ('request_rejected', 'Investment Request Rejected'), ('payment_received', 'Payment Received'), ('roi_update', 'ROI Update')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='Investor.investordocument')),
                ('related_investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='Investor.investment')),
                ('related_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='Investor.investmentlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('admin_reviewed', 'Admin Reviewed'), ('agent_assigned', 'Agent Assigned'), ('document_verified', 'Document Verified'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('document_verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('agent_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('investment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='Investor.investment')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_requests', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_requests', to='Investor.investmentlisting')),
            ],
            options={
                'unique_together': {('investor', 'listing')},
            },
        ),
        migrations.CreateModel(
            name='PropertyValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_date', models.DateField(help_text='Date of valuation')),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Current market value', max_digits=15)),
                ('appreciation_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Annual appreciation rate percentage', max_digits=5, null=True)),
                ('valuation_method', models.CharField(choices=[('comparative', 'Comparative Market Analysis'), ('income', 'Income Capitalization'), ('cost', 'Cost Approach'), ('professional', 'Professional Appraisal')], default='comparative', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='PublicPage.property')),
                ('valuator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_valuations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-valuation_date'],
                'unique_together': {('property_obj', 'valuation_date')},
            },
        ),
        migrations.CreateModel(
            name='ROIHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(help_text='Date of ROI record')),
                ('roi_percentage', models.DecimalField(decimal_places=2, help_text='ROI percentage at this point', max_digits=5)),
                ('cumulative_returns', models.DecimalField(decimal_places=2, help_text='Cumulative returns to date', max_digits=15)),
                ('monthly_return', models.DecimalField(blank=True, decimal_places=2, help_text='Return for this month', max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_history', to='Investor.investment')),
            ],
            options={
                'ordering': ['-record_date'],
                'unique_together': {('investment', 'record_date')},
            },
        ),
    ]
