# Generated by Django 5.2.15 on 2026-06-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0002_investment_current_value_investment_exit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='investment_duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='investment_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='max_investment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='min_investment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='preferred_investment_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
