"""
Django settings for HeyDayRealty project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost, x-realtors.in').split(',')

# CSRF trusted origins for HTTPS
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'https://x-realtors.in').split(',')


# Application definition

INSTALLED_APPS = [
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    
    # Third-party apps
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'corsheaders',
    
    # Custom Apps
    'Apps.PublicPage',
    'Apps.Customer',
    'Apps.Investor',
    'Apps.Administration',
    'Apps.Agent',
    'Apps.buy',
    'Apps.sell',
    'Apps.Subscriptions',
    'Apps.Organization',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Apps.Administration.middleware.SessionTimeoutMiddleware',
    'Apps.Administration.middleware.AgentKYCMiddleware',
]

ROOT_URLCONF = 'HeyDayRealty.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                 ],
        },
    },
]

WSGI_APPLICATION = 'HeyDayRealty.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.postgresql')

if DB_ENGINE == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': os.getenv('DB_NAME',  default='heyday_db'),
            'USER': os.getenv('DB_USER',  default='postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD',  default='postgres'),
            'HOST': os.getenv('DB_HOST',  default='postgres'),
            'PORT': os.getenv('DB_PORT', default='5432'),
        }
    }

print(f"Using database engine: {DATABASES}")
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'


USE_I18N = True

USE_TZ = True


# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'Apps.Administration.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Cashfree API Settings

CASHFREE_APP_ID = os.getenv('CASHFREE_APP_ID')
CASHFREE_SECRET_KEY = os.getenv('CASHFREE_SECRET_KEY')
CASHFREE_ENVIRONMENT = os.getenv('CASHFREE_ENVIRONMENT')  # Set to "PRODUCTION" when going live

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'staticfiles')]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'HHectare API',
    'DESCRIPTION': 'Comprehensive API for HHectare platform including Administration, Customer, Investor, Agent, and Property management',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_NO_READ_ONLY_REQUIRED': True,
    'TAGS': [
        {
            'name': 'Administration',
            'description': 'Admin dashboard, user management, system settings, and contact inquiry APIs'
        },
        {
            'name': 'Contact Inquiry',
            'description': 'Public contact form submissions from multiple websites'
        },
        {
            'name': 'Customer',
            'description': 'Customer-facing APIs for property browsing and inquiries'
        },
        {
            'name': 'Investor',
            'description': 'Investor portal APIs for investment management'
        },
        {
            'name': 'Agent',
            'description': 'Agent dashboard and property management APIs'
        },
        {
            'name': 'Properties',
            'description': 'Property listing, search, and management APIs'
        },
        {
            'name': 'Authentication',
            'description': 'User authentication and authorization'
        },
    ],
}

# Authentication Settings
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/dashboard/'  # Smart dashboard will redirect based on role
LOGOUT_REDIRECT_URL = '/auth/login/'


# Email settings
EMAIL_BACKEND = 'Apps.Administration.email_backend.SystemSettingsEmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@heydayrealty.com'

# Site branding / display metadata
SITE_NAME = 'HHectare'
SITE_SLOGAN = 'Invest Green. Grow Strong.'
SITE_DESCRIPTION = 'HHectare — Invest Green. Grow Strong. Premium real estate platform offering residential, commercial, luxury, and agricultural properties with verified listings across India.'

# Upload limits (aligned with nginx client_max_body_size 50M)
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB before spilling to disk
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

# Contact API Keys for external website submissions
CONTACT_API_KEY_HEYDAY = os.getenv('CONTACT_API_KEY_HEYDAY')
CONTACT_API_KEY_CODIQ = os.getenv('CONTACT_API_KEY_CODIQ')

# CORS Settings - Allow all origins for API
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://x-realtors.in",
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-api-key',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Storj.io (S3 Compatible) Storage Configuration
# Make sure to add these to your .env file

# CRITICAL FIX: boto3 >= 1.36 uses streaming trailer checksums by default,
# which Storj and other S3-compatible gateways don't support.
# This must be set BEFORE boto3 is imported/used.
os.environ.setdefault('AWS_REQUEST_CHECKSUM_CALCULATION', 'when_required')
os.environ.setdefault('AWS_RESPONSE_CHECKSUM_VALIDATION', 'when_required')

AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL', 'https://gateway.storjshare.io')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1') # Usually ignored by Storj, but required by boto3
AWS_DEFAULT_ACL = None # Storj usually manages access via grants/policies
AWS_S3_FILE_OVERWRITE = False

# Role-based Bucket Names
AWS_AGENT_BUCKET_NAME = os.getenv('AWS_AGENT_BUCKET_NAME', 'heyday-agent')
AWS_CUSTOMER_BUCKET_NAME = os.getenv('AWS_CUSTOMER_BUCKET_NAME', 'heyday-customer')
AWS_ADMIN_BUCKET_NAME = os.getenv('AWS_ADMIN_BUCKET_NAME', 'heyday-admin')
AWS_PROPERTY_BUCKET_NAME = os.getenv('AWS_PROPERTY_BUCKET_NAME', 'heyday-property')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', 'heyday-general')

# Set default storage to General for everything else not explicitly set
DEFAULT_FILE_STORAGE = 'HeyDayRealty.storage_backends.GeneralMediaStorage'
